# Generated by Django 4.1.3 on 2023-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_genre_hobi_remove_profile_nama_profile_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hobi',
            name='hobi',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
